name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --extras "testing"

      - name: Run pytest
        run: |
          poetry run pytest --cov=teenytiny -s -v
      
      - name: Run security checks
        run: |
          poetry run bandit -r teenytiny

