name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --extras "testing"

      - name: Run pytest
        run: |
          poetry run pytest --cov=teenytiny -s -v

      - name: Build the package
        run: |
          poetry build

      - name: Publish to PyPI
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --repository testpypi --skip-existing --no-interaction
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.PYPI_PASSWORD }}
